name: Create PDF Handout

on: push

env:
  CLASS_NAME: OOP-WS2020-
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  convert_handout_via_pandoc:
    runs-on: ubuntu-latest
    container: docker://pandoc/latex:2.9
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: tlmgr install german
      - name: Build Document
        run: pandoc --output=$CLASS_NAME$REPO_NAME.pdf Readme.md
      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: pdf
          path: ${{ env.CLASS_NAME }}${{ env.REPO_NAME}}.pdf
  commit_handout_to_repo:
    runs-on: ubuntu-latest
    needs: convert_handout_via_pandoc
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: pdf
      - name: Add And Commit
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: "*.pdf"
          message: "Automatisch erzeugtes Handout-PDF hinzugef√ºgt"
